name: Deploy to GitHub Pages (main/docs)

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      # Keep this if you've committed package-lock.json; otherwise swap to `npm install`
      - name: Install dependencies
        run: npm ci

      - name: Build (Next.js static export)
        env:
          NODE_ENV: production
        run: |
          npm run build
          touch out/.nojekyll
          echo "=== out tree ==="
          ls -R out

      - name: Deploy to /docs on main
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: out
          target-folder: docs
          clean: true
